// Generated by CoffeeScript 1.10.0
(function() {
  var Person, WebDeveloper,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Person = (function() {
    function Person(name, age) {
      this.name = name;
      this.age = age;
    }

    Person.prototype.getInfo = function() {
      return "Name " + this.name + ", Age " + this.age;
    };

    return Person;

  })();

  Person = (function() {
    function Person(name1, age1) {
      this.name = name1;
      this.age = age1;
    }

    Person.prototype.getInfo = function() {
      return "Name " + this.name + ", Age " + this.age;
    };

    return Person;

  })();

  Person = (function() {
    function Person(name1, age1) {
      this.name = name1;
      this.age = age1;
    }

    Person.prototype.getInfo = function() {
      return "Name " + this.name + ", Age " + this.age;
    };

    Person.myStatic = function() {
      return something();
    };

    return Person;

  })();

  Person = (function() {
    function Person(name1, age1) {
      this.name = name1;
      this.age = age1;
    }

    Person.prototype.getInfo = function() {
      return "Name " + this.name + ", Age " + this.age;
    };

    Person.myStaticNum = 12324;

    return Person;

  })();

  WebDeveloper = (function(superClass) {
    extend(WebDeveloper, superClass);

    function WebDeveloper() {
      return WebDeveloper.__super__.constructor.apply(this, arguments);
    }

    return WebDeveloper;

  })(Person);

  WebDeveloper = (function(superClass) {
    extend(WebDeveloper, superClass);

    function WebDeveloper() {
      something();
    }

    return WebDeveloper;

  })(Person);

  WebDeveloper = (function(superClass) {
    extend(WebDeveloper, superClass);

    function WebDeveloper() {
      WebDeveloper.__super__.constructor.apply(this, arguments);
      something();
    }

    return WebDeveloper;

  })(Person);

  WebDeveloper = (function(superClass) {
    extend(WebDeveloper, superClass);

    function WebDeveloper() {
      WebDeveloper.__super__.constructor.call(this, 10, 20, 30);
      something();
    }

    return WebDeveloper;

  })(Person);

  WebDeveloper = (function(superClass) {
    extend(WebDeveloper, superClass);

    function WebDeveloper() {
      WebDeveloper.__super__.constructor.call(this, 10, 20, 30);
      something();
    }

    WebDeveloper.prototype.getInfo = function() {
      return "my Custom getInfo";
    };

    return WebDeveloper;

  })(Person);

  WebDeveloper = (function(superClass) {
    extend(WebDeveloper, superClass);

    function WebDeveloper() {
      WebDeveloper.__super__.constructor.call(this, 10, 20, 30);
      something();
    }

    WebDeveloper.prototype.getInfo = function() {
      WebDeveloper.__super__.getInfo.apply(this, arguments);
      return "my Custom getInfo";
    };

    return WebDeveloper;

  })(Person);

  WebDeveloper = (function(superClass) {
    extend(WebDeveloper, superClass);

    function WebDeveloper() {
      WebDeveloper.__super__.constructor.call(this, 10, 20, 30);
      something();
    }

    WebDeveloper.prototype.getInfo = function() {
      WebDeveloper.__super__.getInfo.call(this, arg1, arg2);
      return "my Custom getInfo";
    };

    return WebDeveloper;

  })(Person);

  Person.prototype.myMethod = function() {
    return say("hi");
  };


  /*
    Person.prototype.myMethod = function() {
      return say("hi");
    };
   */


  /*
  var that = this;
  var _self = this;
  var _this = this;
   */

  WebDeveloper = (function(superClass) {
    extend(WebDeveloper, superClass);

    function WebDeveloper() {
      WebDeveloper.__super__.constructor.call(this, 10, 20, 30);
      something();
    }

    WebDeveloper.prototype.myMethod = function() {
      return someFunc(function() {
        return process(this.age);
      });
    };

    return WebDeveloper;

  })(Person);

  WebDeveloper = (function(superClass) {
    extend(WebDeveloper, superClass);

    function WebDeveloper() {
      WebDeveloper.__super__.constructor.call(this, 10, 20, 30);
      something();
    }

    WebDeveloper.prototype.myMethod = function() {
      var _this;
      _this = this;
      return someFunc(function() {
        return process(_this.age);
      });
    };

    return WebDeveloper;

  })(Person);

  WebDeveloper = (function(superClass) {
    extend(WebDeveloper, superClass);

    function WebDeveloper() {
      WebDeveloper.__super__.constructor.call(this, 10, 20, 30);
      something();
    }

    WebDeveloper.prototype.myMethod = function() {
      return someFunc((function(_this) {
        return function() {
          return process(_this.age);
        };
      })(this));
    };

    return WebDeveloper;

  })(Person);

}).call(this);
