// Generated by CoffeeScript 1.10.0
(function() {
  var action, message;

  if (isReady) {
    activate(something);
  }

  if (isReady) {
    activate(something);
    if (!isFull) {
      append(something);
    }
  }

  if (isReady) {
    activate(something);
    if (!isFull) {
      append(something);
    }
  } else {
    prepare();
  }

  if (isReady) {
    activate(something);
  }

  if (isReady) {
    activate(something);
  }

  if (isReady) {
    activate(something);
    if (!isFull) {
      append(something);
    }
  }

  if (!isReady) {
    prepare();
  }

  if (!isReady) {
    prepare();
  }

  action = mode === "Idle" ? "sleep" : "wander";

  show(message ? message : warning);

  switch (state) {
    case 0:
      message = "request not initialize";
      break;
    case 1:
      message = "server connection established";
      break;
    case 2:
      message = "request received";
      break;
    case 3:
      message = "procession request";
      break;
    case 4:
      message = "request finished and response is ready";
      break;
    default:
      message = "unknown state";
  }

  message = (function() {
    switch (state) {
      case 0:
        return "request not initialize";
      case 1:
        return "server connection established";
      case 2:
        return "request received";
      case 3:
        return "procession request";
      case 4:
        return "request finished and response is ready";
      default:
        return message = "unknown state";
    }
  })();

  console.log("Message [" + state + "] " + ((function() {
    switch (state) {
      case 0:
        return 'request not initialize';
      case 1:
        return 'server connection established';
      case 2:
        return 'request received';
      case 3:
        return 'procession request';
      case 4:
        return 'request finished and response is ready';
      default:
        return 'unknown state';
    }
  })()));

}).call(this);
