// Generated by CoffeeScript 1.10.0
(function() {
  var a, author, b, book, car, model, object, pages, range, ref, ref1, ref2, ref3, type, user2,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  first && second;

  true || false;

  first && second;

  true || false;

  !isReady || !isOnline;

  a === b;

  a !== b;

  a === b;

  a !== b;

  a !== b;

  a === !b;

  (10 < a && a < 20);

  if ((10 < a && a < 20)) {
    update(a);
  }


  /*
  if ((10 < a && a < 20)) {
  	update(a);
  }
   */

  ref = [b, a], a = ref[0], b = ref[1];

  ref1 = ["1984", "G.Orwell", 327], book = ref1[0], author = ref1[1], pages = ref1[2];

  car = {
    make: "Porsche",
    model: "911 Turbo",
    engine: {
      type: "V8",
      hp: 478
    },
    cost: 600000
  };

  model = car.model, (ref2 = car.engine, type = ref2.type);

  user2 = {
    name: "John",
    age: 20,
    lastVisit: Date.now()
  };

  "age" in user2;

  range = [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20];

  indexOf.call(range, 15) >= 0;

  country === "Russia" || country === "USA" || country === "UK" || country === "Germany";


  /* 
    country === "Russia" || country === "USA" || country === "UK" || country === "Germany";
   */

  book = 3435;

  open(book);

  if (book) {
    open(book);
  }

  if (book != null) {
    open(book);
  }

  if (book !== null) {
    open(book);
  }

  if (book !== null) {
    if (typeof open === "function") {
      open(book);
    }
  }

  object = {};

  if (object.speed == null) {
    object.speed = 100;
  }

  this.age = config.age || 10;

  this.age = (ref3 = config.age) != null ? ref3 : 10;

  object.speed = object.speed || 100;

  object.speed || (object.speed = 100);

  object.speed || (object.speed = 100);

  object.speed && (object.speed = 100);

  object.speed && (object.speed = 100);

}).call(this);
