// Generated by CoffeeScript 1.10.0

/*
Multiline
comment
in coffee
script
 */

(function() {
  var a, americanExpress, array, array2, array3, array4, array5, array6, array7, b, bool, bool1, bool2, bool3, bool4, bool5, bool6, fewLinesString, greeting, greeting2, heredocString, i, mastercard, name, name2, newArray, oneLineString, results, user, visa;

  a = 10;

  b = 20;

  bool = true;

  bool1 = true;

  bool2 = true;

  bool3 = true;

  bool4 = false;

  bool5 = false;

  bool6 = false;

  oneLineString = "Some very long multiline string";

  fewLinesString = 'Some very long multiline string';

  heredocString = "Some more text with\nspecial symbols\nfor converting it\nin valid JavaScript";

  heredocString = 'Some more text with\nspecial symbols\nfor converting it\nin valid JavaScript';

  name = "Myname";

  greeting = "Hello " + name + "!";

  name2 = "userName";

  greeting2 = "Hi " + name2 + "!";

  name2 = "userName";

  greeting2 = "Hi " + (name2.toUpperCase()) + "!";

  name2 = "userName";

  greeting2 = 'Hi #{name2.toUpperCase()}!';

  array = [1, 2, 3, 4, 5, 6, 7, 8, 9];

  array = [1, 2, 3, 4, 5, 6, 7, 8, 9];

  array2 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  array3 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];

  array4 = (function() {
    results = [];
    for (i = 20; i <= 90; i++){ results.push(i); }
    return results;
  }).apply(this);

  array5 = [-90, -89, -88, -87, -86, -85, -84, -83, -82, -81, -80];

  array6 = [20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5];

  array7 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  array7.slice(5, 11);

  array7.slice(5, 10);

  array7.slice(0, 9);

  array7.slice(5);

  array7.slice(0);

  newArray = array7.slice(0);

  user = {
    name: "John Smith",
    age: 22,
    status: "Web Developer",
    skills: {
      html: 10,
      css: 9,
      javascript: 6,
      coffeescript: 4
    }
  };

  visa = /^4[0-9]{12}(?:[0-9]{3})?$/;

  mastercard = /^5[1-5][0-9]{14}$/;

  americanExpress = /^3[47][0-9]{13}$/;

  visa = /^4[0-9]{12}(?:[0-9]{3})?$/;

  mastercard = /^5[1-5][0-9]{14}$/;

  americanExpress = /^3[47][0-9]{13}$/;

}).call(this);
